FILE_TYPE_CHOICES = (
('', 'None'),
('swf', 'Adobe Flash (.swf)'),
('pdf', 'Adobe Portable Document Format (.pdf)'),
('ps', 'Adobe PostScript (.ps)'),
('dwf', 'Autodesk Design Web Format (.dwf)'),
('kml', 'Google Earth (.kml, .kmz)'),
('gpx', 'GPS eXchange Format (.gpx)'),
('hwp', 'Hancom Hanword (.hwp)'),
('htm', 'HTML (.htm, .html)'),
('xls', 'Microsoft Exel (.xls, .xlsx)'),
('ppt', 'Microsoft PowerPoint (.ppt, .pptx)'),
('doc', 'Microsoft Word (.doc, .docx)'),
('odp', 'OpenOffice presentation (.odp)'),
('ods', 'OpenOffice spreadsheet (.ods)'),
('odt', 'OpenOffice text (.odt)'),
('rtf', 'Rich Text Format (.rtf)'),
('svg', 'Scalable Vector Graphics (.svg)'),
('tex', 'Tex/LaTeX (.tex)'),
('txt', 'Text (.txt, .text, including source code extentions in common programming language)'),
('bas', 'Basic source code (.bas)'),
('c', 'C/C++ source code (.c, .cc, .cpp, .cxx, .h, .hpp)'),
('cs', 'C# source code (.cs)'),
('java', 'Java source code (.java)'),
('pl', 'Perl source code (.pl)'),
('py', 'Python souce code (.py)'),
('wml', 'Wireless Markup Language (.wml, .wap)'),
('xml', 'XML (.xml)'))


GL_CHOICES = (('', 'None'),
('af','Afghanistan '),
('al','Albania '),
('dz','Algeria '),
('as','American Samoa '),
('ad','Andorra '),
('ao','Angola '),
('ai','Anguilla '),
('aq','Antarctica '),
('ag','Antigua and Barbuda '),
('ar','Argentina '),
('am','Armenia '),
('aw','Aruba '),
('au','Australia '),
('at','Austria '),
('az','Azerbaijan '),
('bs','Bahamas '),
('bh','Bahrain '),
('bd','Bangladesh '),
('bb','Barbados '),
('by','Belarus '),
('be','Belgium '),
('bz','Belize '),
('bj','Benin '),
('bm','Bermuda '),
('bt','Bhutan '),
('bo','Bolivia '),
('ba','Bosnia and Herzegovina '),
('bw','Botswana '),
('bv','Bouvet Island '),
('br','Brazil '),
('io','British Indian Ocean Territory '),
('bn','Brunei Darussalam '),
('bg','Bulgaria '),
('bf','Burkina Faso '),
('bi','Burundi '),
('kh','Cambodia '),
('cm','Cameroon '),
('ca','Canada '),
('cv','Cape Verde '),
('ky','Cayman Islands '),
('cf','Central African Republic '),
('td','Chad '),
('cl','Chile '),
('cn','China '),
('cx','Christmas Island '),
('cc','Cocos (Keeling) Islands '),
('co','Colombia '),
('km','Comoros '),
('cg','Congo '),
('cd', 'Congo, the Democratic Republic of the '),
('ck','Cook Islands '),
('cr','Costa Rica '),
('ci','Cote D\'ivoire '),
('hr','Croatia '),
('cu','Cuba '),
('cy','Cyprus '),
('cz','Czech Republic '),
('dk','Denmark '),
('dj','Djibouti '),
('dm','Dominica '),
('do','Dominican Republic '),
('ec','Ecuador '),
('eg','Egypt '),
('sv','El Salvador '),
('gq','Equatorial Guinea '),
('er','Eritrea '),
('ee','Estonia '),
('et','Ethiopia '),
('fk','Falkland Islands (Malvinas) '),
('fo','Faroe Islands '),
('fj','Fiji '),
('fi','Finland '),
('fr','France '),
('gf','French Guiana '),
('pf','French Polynesia '),
('tf','French Southern Territories '),
('ga','Gabon '),
('gm','Gambia '),
('ge','Georgia '),
('de','Germany '),
('gh','Ghana '),
('gi','Gibraltar '),
('gr','Greece '),
('gl','Greenland '),
('gd','Grenada '),
('gp','Guadeloupe '),
('gu','Guam '),
('gt','Guatemala '),
('gn','Guinea '),
('gw','Guinea-Bissau '),
('gy','Guyana '),
('ht','Haiti '),
('hm','Heard Island and Mcdonald Islands '),
('va','Holy See (Vatican City State) '),
('hn','Honduras '),
('hk','Hong Kong '),
('hu','Hungary '),
('is','Iceland '),
('in','India '),
('id','Indonesia '),
('ir', 'Iran, Islamic Republic of '),
('iq','Iraq '),
('ie','Ireland '),
('il','Israel '),
('it','Italy '),
('jm','Jamaica '),
('jp','Japan '),
('jo','Jordan '),
('kz','Kazakhstan '),
('ke','Kenya '),
('ki','Kiribati '),
( 'kp', 'Korea, Democratic People\'s Republic of '),
( 'kr', 'Korea, Republic of '),
('kw','Kuwait '),
('kg','Kyrgyzstan '),
('la','Lao People\'s Democratic Republic '),
('lv','Latvia '),
('lb','Lebanon '),
('ls','Lesotho '),
('lr','Liberia '),
('ly','Libyan Arab Jamahiriya '),
('li','Liechtenstein '),
('lt','Lithuania '),
('lu','Luxembourg '),
('mo','Macao '),
('mk','Macedonia, the Former Yugosalv Republic of '),
('mg','Madagascar '),
('mw','Malawi '),
('my','Malaysia '),
('mv','Maldives '),
('ml','Mali '),
('mt','Malta '),
('mh','Marshall Islands '),
('mq','Martinique '),
('mr','Mauritania '),
('mu','Mauritius '),
('yt','Mayotte '),
('mx','Mexico '),
('fm','Micronesia, Federated States of '),
('md','Moldova, Republic of '),
('mc','Monaco '),
('mn','Mongolia '),
('ms','Montserrat '),
('ma','Morocco '),
('mz','Mozambique '),
('mm','Myanmar '),
('na','Namibia '),
('nr','Nauru '),
('np','Nepal '),
('nl','Netherlands '),
('an','Netherlands Antilles '),
('nc','New Caledonia '),
('nz','New Zealand '),
('ni','Nicaragua '),
('ne','Niger '),
('ng','Nigeria '),
('nu','Niue '),
('nf','Norfolk Island '),
('mp','Northern Mariana Islands '),
('no','Norway '),
('om','Oman '),
('pk','Pakistan '),
('pw','Palau '),
('ps','Palestinian Territory, Occupied '),
('pa','Panama '),
('pg','Papua New Guinea '),
('py','Paraguay '),
('pe','Peru '),
('ph','Philippines '),
('pn','Pitcairn '),
('pl','Poland '),
('pt','Portugal '),
('pr','Puerto Rico '),
('qa','Qatar '),
('re','Reunion '),
('ro','Romania '),
('ru','Russian Federation '),
('rw','Rwanda '),
('sh','Saint Helena '),
('kn','Saint Kitts and Nevis '),
('lc','Saint Lucia '),
('pm','Saint Pierre and Miquelon '),
('vc','Saint Vincent and the Grenadines '),
('ws','Samoa '),
('sm','San Marino '),
('st','Sao Tome and Principe '),
('sa','Saudi Arabia '),
('sn','Senegal '),
('cs','Serbia and Montenegro '),
('sc','Seychelles '),
('sl','Sierra Leone '),
('sg','Singapore '),
('sk','Slovakia '),
('si','Slovenia '),
('sb','Solomon Islands '),
('so','Somalia '),
('za','South Africa '),
('gs','South Georgia and the South Sandwich Islands '),
('es','Spain '),
('lk','Sri Lanka '),
('sd','Sudan '),
('sr','Suriname '),
('sj','Svalbard and Jan Mayen '),
('sz','Swaziland '),
('se','Sweden '),
('ch','Switzerland '),
('sy','Syrian Arab Republic '),
('tw','Taiwan, Province of China '),
('tj','Tajikistan '),
('tz','Tanzania, United Republic of '),
('th','Thailand '),
('tl','Timor-Leste '),
('tg','Togo '),
('tk','Tokelau '),
('to','Tonga '),
('tt','Trinidad and Tobago '),
('tn','Tunisia '),
('tr','Turkey '),
('tm','Turkmenistan '),
('tc','Turks and Caicos Islands '),
('tv','Tuvalu '),
('ug','Uganda '),
('ua','Ukraine '),
('ae','United Arab Emirates '),
('uk','United Kingdom '),
('us','United States '),
('um','United States Minor Outlying Islands '),
('uy','Uruguay '),
('uz','Uzbekistan '),
('vu','Vanuatu '),
('ve','Venezuela '),
('vn','Viet Nam '),
('vg','Virgin Island, British '),
('vi','Virgin Islands, US '),
('wf','Wallis and Futuna '),
('eh','Western Sahara '),
('ye','Yemen '),
('zm','Zambia '),
('zw','Zimbabwe '),)



LR_CHOICES =(('lang_ar','Arabic'), 
('lang_bg','Bulgarian '),
('lang_ca','Catalan '),
('lang_zh-CN','Chinese (Simplified) '),
('lang_zh-TW','Chinese (Traditional) '),
('lang_hr','Croatian '),
('lang_cs','Czech '),
('lang_da','Danish '),
('lang_nl','Dutch '),
('lang_en','English '),
('lang_et','Estonian '),
('lang_fi','Finnish '),
('lang_fr','French '),
('lang_de','German '),
('lang_el','Greek '),
('lang_iw','Hebrew '),
('lang_hu','Hungarian '),
('lang_is','Icelandic '),
('lang_id','Indonesian '),
('lang_it','Italian '),
('lang_ja','Japanese '),
('lang_ko','Korean '),
('lang_lv','Latvian '),
('lang_lt','Lithuanian '),
('lang_no','Norwegian '),
('lang_pl','Polish '),
('lang_pt','Portuguese '),
('lang_ro','Romanian '),
('lang_ru','Russian '),
('lang_sr','Serbian '),
('lang_sk','Slovak '),
('lang_sl','Slovenian '),
('lang_es','Spanish '),
('lang_sv','Swedish '),
('lang_tr','Turkish '))

SORT_CHOICES = (('', 'None'),
    ('date', 'Sort by date'))

SEARCH_CHOICES = (('', 'Search the webpages'),
    ('image', 'Search images'))
